### ISSUE TITLE
How to configure keyboard shortcut

### ISSUE THREAD

**Issue by kbdluv** [bbuck/tab-pinner#1]
Hi!

Sorry if it's obvious and I missed it, but is there a way to configure the keyboard shortcut? I don't see an "Options" link in the Manage Extensions tab.

Thank you for this very useful extension!

**Comment by copejon** [comment]
Chrome Ver: Version 66.0.3359.117 (Official Build) (64-bit)

Options menu item is greyed out.

**Comment by bbuck** [comment]
If you head over to `chrome://extensions` in your browser you can then click on the hamburger menu icon in the top-left and choose "Keyboard Shortcuts" from that menu.

Somewhere in the list you should see that you can set your keyboard shortcuts for Tab Pinner.
