### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by TomGranot** [bbuck/tab-pinner#3]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>X</kbd> is my new favorite shortcut!

Feel free to close, it just felt that more than a star is deserved here.

**Comment by bbuck** [comment]
Thanks for reaching out! I really appreciate. I wanted this feature for myself which is what led me to build it. I'm just happy to see that I'm not the only person that wanted this support! Still perplexed it's not natively implemented years later!
